### ISSUE TITLE
KenLM arpa file

### ISSUE THREAD

**Issue by vidhishanair** [Websail-NU/torch-defseq#1]
Hi,
I'm looking to reproduce this paper. I'd like to know what data was the LM trained on for the ARPA file? Could you probably share the the ARPA file used for reranking?

**Comment by northanapon** [comment]
Hello. You can generate ARPA file using [SRILM's ngram-count](http://www.speech.sri.com/projects/srilm/manpages/ngram-count.1.html). We trained the n-gram language model (3-gram) using only the definition portion from the training data. 

You can find the model that we used [here](http://downey-n1.cs.northwestern.edu/downloads/dm_ngram.tar.gz).

**Comment by vidhishanair** [comment]
Great! This is of great help. Thank you.
