### ISSUE TITLE
what the mean of mode option ”sen“ and”rI“？

### ISSUE THREAD

**Issue by Haitons** [Websail-NU/torch-defseq#2]

**Comment by northanapon** [comment]
`sen` refers to a normal language model mode where we only provide the word being defined as a start of a sequence. On the other hand, `ri` refers to a mode where we use word being defined to make a prediction on every time steps (in addition to the start of a sequence).

**Comment by Haitons** [comment]
@northanapon Thank you very much！But when I set the mode to ri I got the following error：./util/LMHelper.lua:115: bad argument 1 to 'copy' (torch.*Tensor expected, got nil)
stack traceback:
	[C]: in function 'copy'
	./util/LMHelper.lua:115: in function 'predict'
	train.lua:170: in function 'opfunc'
	/home/haiton/torch/install/share/lua/5.1/optim/sgd.lua:44: in function </home/haiton/torch/install/share/lua/5.1/optim/sgd.lua:27>
	train.lua:249: in main chunk
	[C]: in function 'dofile'
	...iton/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Another Ploblem........I set the mode RiCharCNN to true I got this error：
 ./util/CharacterMap.lua:25: attempt to index local 'indexes' (a nil value)
stack traceback:
	./util/CharacterMap.lua:25: in function 'getCharSeqs'
	./util/LMHelper.lua:124: in function 'predict'
	train.lua:170: in function 'opfunc'
	/home/haiton/torch/install/share/lua/5.1/optim/sgd.lua:44: in function </home/haiton/torch/install/share/lua/5.1/optim/sgd.lua:27>
	train.lua:249: in main chunk
	[C]: in function 'dofile'
	...iton/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Can you help me with your answer?

**Comment by northanapon** [comment]
I think there might be something wrong with the setting. Can you try the following command?

`th train.lua --dataType labeled --rho -1 --batchSize 50 --optim adam --learningRate 0.001 --modelDir tmp_exp --mode ri --RIMode gated  --hiddenSizes "{300, 300}" --RICharCNN --RIMode gated --cudnnCNN`

**Comment by Haitons** [comment]
@northanapon Yeah,thank you，this problem has been solved.And what kind of data does the **datatype:** `labeled` and `sequence` mean?

**Comment by northanapon** [comment]
This refers to how the code will read the data. `sequence` means a simple text. `labeled` means extra condition (word being defined). I think I used `labeled` all the time.

**Comment by Haitons** [comment]
@northanapon OK，Thank you for your patience.
